exports.downloader = require('./downloader')
exports.meme = require('./meme')
exports.removebg = require('./remove-bg')
exports.urlShortener = require('./shortener')
exports.translate = require('./translate')
exports.stext = require('./stickertext')
exports.cariKasar = require('./kataKotor')
exports.scraper = require('./scraper')
